version: "3.8"

services:
  #backend service
  api:
    build: ./server
    container_name: ebook_server
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - mynetwork

  #frontend service
  ui:
    build: ./client
    container_name: ebook_ui
    ports:
      - 3000:3000
    depends_on:
      - api
    env_file:
      - ./client/.env
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
